services:
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: dashboard
      POSTGRES_DB: dashboard-postgres
    volumes:
      - dashboard-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - dashboard-redis-data:/data

volumes:
  dashboard-postgres-data:
  dashboard-redis-data:
